### ISSUE TITLE
[FEATURE] Main Activity 의 탭에 두개의 Fragment를 연결, Issues Fragment에 Api 연동 확인

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#11]
## 📝  To-do

- [x] MainActivity에 IssueFragment, NotificationsFragment 연동
- [x] 기존 코드와 문제 없이 호환되는지 확인
- [x] Device 방향 전환시 선택중인 탭이 유지되는지 확인
- [x] 이미 선택중인 탭을 다시 선택했을때 원하는 동작이 발생하는지 확인
- [x] ApiService 생성 방식의 변경을 GithubIssuesService 생성 코드에 적용
- [x] IssuesFragment Api 연동 오류 해결

## 📆 Date

07.13 23:00 - 07.13 23.59 (작업시간 약 1시간 예상)
