### ISSUE TITLE
[FEATURE] Sign In 화면 임시 코드 제거 및 기능, 디자인 구현

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#13]
## 📝  To-do

- [ ] Sign In 임시 코드 제거
- [ ] Sign In 에서 사용되는 Api 코드 추가, 정리, 개선
- [ ] Sign In 화면 디자인 적용
- [ ] Url Scheme 처리 코드 수정

## 📆 Date

07.14 00:00 - 07.14 02:00 (예상 작업시간 2시간)
