### ISSUE TITLE
[FEATURE] 검색 화면 구현 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#15]
## 📝  To-do

- [x] 화면에 진입하면 자동으로 키보드가 올라오며 검색창에 포커스가 들어간다
- [x] Search Api 연동
- [x] Item View 구현
- [x] 페이징 처리
- [x] 검색 화면 디자인

## 📆 Date

07.14 10:20 - 07.14: 17:00 (예상 작업시간 6시간)
