### ISSUE TITLE
[FEATURE] 검색 아이템 뷰 - Repository 개발 언어에 따른 색상 구현 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#18]
## 📝  To-do

- [x] 개발 언어 별로 색깔 구분
- [x] 개발 언어가 입력되어 있지 않은 저장소의 경우 처리
- [x] 색상은 랜덤하게 부여되지만, 개발 언어 별로 색상이 구분되어야 한다

## 📆 Date

07.18 16:00 - 07.18 18:30 (예상 작업시간 2시간 30분)
