### ISSUE TITLE
[REFACTOR] Issues Api 코드 리팩토링, 수정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#19]
### [REFACTOR] Issues Api 코드 리팩토링 , 수정
AppContainer 에 repository 구현체 인스턴스 생성하는 코드를
Service Locator 패턴으로 변경
Issue Api 에 filter 매개변수 추가

## 📝  To-do

- [x] Service Locator 패턴으로 변경
- [x] Issue Api 에 filter 매개변수 추가
- [x] Issue Number 추가
- [x] Issue repository title 의 값을 full name으로 변경 
- [x] Github Issue Response 의 의미를 List가 아닌 각 Item을 의미하도록 변경

## 📆 Date

미정
