### ISSUE TITLE
[FEATURE] Search Api 쿼리 제한 확인 및 개선 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#21]
## 📝  To-do

- [x] 쿼리 제한이 실제로 적용되고 있는지 테스트
- [x] 쿼리 제한 확인 api 를 통한 실시간 확인( https://docs.github.com/en/rest/rate-limit )
- [x] 엔터키를 통한 검색 방식에서 디바운스 처리 방식으로 변경에 대한 고민
- [x] 페이징 로딩중 처리를 에러를 뿜지도록 수정 (페이징 이벤트가 민감해서 너무 많은 에러가 뿜어지는 문제 발견)
- [x] repositoryDescriptor 가 비어서 온다면 보이지 않도록 수정

## 📆 Date

07.16 18:30 - 07.16 20:00 
07.16 22:00 - 07.17 00:00 (예상 작업시간 총 3시간 30분)
