### ISSUE TITLE
[FEATURE] Issues 화면 팝업 메뉴 디자인 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#22]
## 📝  To-do

- [x] 팝업 메뉴 디자인 적용
- [x]  status bar 색상 변경
- [x] 팝업 메뉴 체크 디자인 적용
- [x] 불가능함을 고려하여 스피너 구현으로 전환 고민 및 적용

## 📆 Date

07.15 19:30 - 22:00 ( 예상 작업시간 2시간 30분 )
