### ISSUE TITLE
[REFACTOR] Repository 객체의 의미에 맞게 Api 성공 실패에 대한 판별도 포함하도록 변경 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#26]
## 📝  To-do

- [x] Sign In Repository 리팩토링
- [x] Issues Repository 리팩토링
- [x] Notifications Repository 리팩토링
- [x] Search Repository 리팩토링

## 📆 Date

07.16 14:00 - 07.16 14:30 (예상 작업시간 30분)
