### ISSUE TITLE
[FEATURE] Main 화면에서 git profile api 호출하여 프로필 이미지 가져와 보여주기 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#28]
## 📝  To-do

- [x] GIthub Proifle Api 연동
- [x] 메인화면에서 Profile 정보 불러와 프로필 이미지 보여주기
- [x] 프로필 정보 처리에 대한 고민(프로필 화면에서 따로 호출?, 메인에서 가지고 있는 정보를 전달?), (프로필 이미지가 없을 첫 실행시에만 메인에서 호출?, 매번 메인에서 호출?), (앞의 결정에 따라 프로필 Api 호출 시점이 정해질텐데, 갱신 시점이 부족하지 않을까 고민)

## 📆 Date

07.16 16:30 - 07.16 17:50 (예상 작업 시간 1시간 20분)
