### ISSUE TITLE
[DESIGN] Main Design 적용 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#32]
## 📝  To-do

- [x] 배경화면 그라데이션 적용 - figma 디자인 코드를 보고 유추하여 작성했지만, 별 다른게 없는 것 같다
- [x] 메인 탭 버튼들이 선택된 상태에서 클릭시 원하는대로 색상변화가 되고 있지 않은 부분 수정
- [x] 검색 화면 왼쪽 검색 아이콘이, focus 가 들어가면 gone 처리 되도록 수정
- [x] 검색화면 터치시 키보드 내려가도록 설정

## 📆 Date

07.16 23:00 - 07.17 00:20 (예상 작업시간 50분)
