### ISSUE TITLE
[FEATURE] Github Profile 화면에 필요한 데이터 요청하도록 Api 수정 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#41]
## 📝  To-do

- [x] private repo count
- [x] OAuth scope 에 user 추가 - private repo count 를 얻어 오기 위함
- [x] repo star count 
- [x] job? tag? 뭔지 모를 데이터 - 나름의 기준을 세워서 뷰에 걸맞게 데이터를 가져오도록 설정

## 📆 Date

07.19 18:00 - 07.19 20:00 (예상 작업시간 2시간 / 실제 작업 시간 30분)
