### ISSUE TITLE
[REFACTOR] Service-Locator 브랜치 세부적인 코드 리팩토링 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#56]
## 📝  To-do

- [x] 서로 다른 스타일로 작성된 부분 일관화
- [x] 개발 도중 누락된 에러처리 수정
- [x] date format 관리 객체 생성하여 필요한 곳에 의존성 주입해서 사용하도록 변경

## 📆 Date

07.21 23:30 - 07.22 00:30 (예상 작업시간 1시간)
