### ISSUE TITLE
[REFACTOR] Search Repository Activity progress 위치 조정, Paging Listener 패키지 이동

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#58]
## 📝  To-do

- [x] Search Repository Activity progress 위치 조정
- [x] Paging Listener 패키지 이동
- [x] DateUtil parse Data 리턴 타입을 not null로 설정

## 📆 Date

07.22 00:10 - 00:13 (3분)
