### ISSUE TITLE
[FEATURE] Main 화면 디자인 작업

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#6]
## 📝  To-do

- [x] theme를 NoActionBar로 설정 후 Toolbar 추가
- [x] 상단에 두개의 버튼 생성 후 디자인, 클릭시 fragment 이동 할 수 있게 설정 준비
- [x] Toolbar 의 프로필 이미지를 기본 이미지로 설정

## 📆 Date

07.13 16:50 - 07:13 18:30 (작업시간 1시간 30분 예상)
