### ISSUE TITLE
[FIX] Issue 탭 문제 수정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-repo-09#60]
## 📝  To-do

- [x] Issue 목록에 우테켐 repo의 Issue가 포함되지 않는 문제 수정
- [x] Issue Item View가 약간 일그러지는 문제 수정
- [x] statue 변경 시 scroll to top 수행하도록 수정

## 📆 Date

07.23 19:15 - 19:40 (25분 예상)
